module.exports = {
  // development: {
  //   logging: false,
  //   logQueryParameters: false,
  //   username: "283342",
  //   password: "@MExpert2022!",
  //   database: "staging-mexpert_db",
  //   host: "mysql-staging-mexpert.alwaysdata.net",
  //   dialect: "mysql",
  // },
  development: {
    logging: false,
    logQueryParameters: false,
    username: "root",
    password: "root",
    database: "mobilexpert",
    host: "127.0.0.1",
    dialect: "mysql",
    port: 8889,
  },
  test: {
    username: "root",
    password: null,
    database: "database_test",
    host: "127.0.0.1",
    dialect: "mysql",
    port: 8889,
  },
  production: {
    logging: false,
    logQueryParameters: false,
    username: "283342",
    password: "@MExpert2022!",
    database: "staging-mexpert_db",
    host: "mysql-staging-mexpert.alwaysdata.net",
    dialect: "mysql",
  },
};
